sudo: required
services:
  - docker

before_install:
  - docker build -t teckgiik101/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run teckgiik101/react-test npm test -- --coverage

after_success:
  - docker build -t teckgiik101/dcac-client ./client
  - docker build -t teckgiik101/dcac-nginx ./nginx
  - docker build -t teckgiik101/dcac-server ./server
  - docker build -t teckgiik101/dcac-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push teckgiik101/dcac-client
  - docker push teckgiik101/dcac-nginx
  - docker push teckgiik101/dcac-server
  - docker push teckgiik101/dcac-worker

deploy:
  provider: elasticbeanstalk
  regoin: "ap-south-1"
  app: "multidoc"
  env: "Multidoc-env"
  bucket_name: "elasticbeanstalk-ap-south-1-411040180627"
  bucket_path: "multidoc"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
